version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-storage:/root/.ollama

  ai-code-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-code-assistant
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434  # Ollama API bağlantısı
    depends_on:
      - ollama  # Ollama servisi önce başlar

volumes:
  ollama-storage:
